{
 "title": "Web Analytics Dashboard",
 "description": "Web Analytics dashboard using preview version of Grafana Loki",
 "tags": [ "loki" ],
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Requests per status code",
   "type": "stat",
   "gridPos": { "h": 5, "w": 15, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (statuscode) (count_over_time({filename=\"/var/log/nginx/access_loki.log\"} | regexp \"HTTP/1.1\\\" (?P<statuscode>\\\\d{3}) \"[$__interval]))"
    }
   ]
  },
  {
   "title": "% of 5xx requests ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(({job=\"nginx_access_log\"} | regexp \"HTTP/1.1\\\" (?P<statuscode>5\\\\d{2}) \" )[$__interval])) / (sum(rate(({job=\"nginx_access_log\"} | regexp \"HTTP/1.1\\\" (?P<statuscode>\\\\d{3})\" )[$__interval])) / 100)"
    }
   ]
  },
  {
   "title": "Total Bytes Sent",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum_over_time({filename=\"/var/log/nginx/access_loki.log\"} | regexp \"HTTP\\\\/1\\\\.1\\\" (?P<statuscode>\\\\d{3}) (?P<value>\\\\d+) (?P<refferer>\\\".*?\\\") \\\"(?P<useragent>.*)\\\"\"[$__interval])"
    }
   ]
  },
  {
   "title": "HTTP requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (statuscode) (count_over_time({filename=\"/var/log/nginx/access_loki.log\"} | regexp \"HTTP/1.1\\\" (?P<statuscode>\\\\d{3}) \"[$__interval]))"
    }
   ]
  },
  {
   "title": "Bytes Sent",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 7, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (host) (sum_over_time({filename=\"/var/log/nginx/access_loki.log\"} | regexp \"HTTP\\\\/1\\\\.1\\\" (?P<statuscode>\\\\d{3}) (?P<value>\\\\d+) (?P<refferer>\\\".*?\\\") \\\"(?P<useragent>.*)\\\"\"[$__interval]))"
    }
   ]
  },
  {
   "title": "Total requests  ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "count_over_time({filename=\"/var/log/nginx/access_loki.log\"}[$__interval])"
    }
   ]
  },
  {
   "title": "% of requests by Googlebot",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": " sum(rate(({job=\"nginx_access_log\"} |= \"Googlebot\")[$__interval])) / (sum(rate(({job=\"nginx_access_log\"} |= \"Mozilla\")[$__interval])) / 100)"
    }
   ]
  },
  {
   "title": "95th percentile of Request Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by(host) (quantile_over_time(0.95,{filename=\"/var/log/nginx/access_loki.log\"} | regexp \"HTTP\\\\/1\\\\.1\\\" \\\\d{3} \\\\d+ \\\".*?\\\" \\\".*\\\" \\\".*?\\\" (?P<value>[-+]?[0-9]*\\\\.?[0-9]+)\"[$__interval]))"
    }
   ]
  },
  {
   "title": "Top Countries",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 9, "w": 15, "x": 0, "y": 18 },
   "valueName": "total",
   "targets": [
    {
     "expr": "sum by (country_code) (count_over_time({filename=\"/var/log/nginx/access_loki.log\"} | regexp \"HTTP\\\\/1\\\\.1\\\" (?P<statuscode>\\\\d{3}) (?P<bytessent>\\\\d+) (?P<refferer>\\\".*?\\\") \\\"(?P<useragent>.*)\\\" \\\"(?P<country_code>.*)\\\"\"[$__interval]))"
    }
   ]
  },
  {
   "title": "Top IPs",
   "type": "table",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 23 },
   "targets": [
    {
     "expr": "topk(5, sum by (ipaddress) (count_over_time({filename=\"/var/log/nginx/access_loki.log\"} | regexp \"(?P<ipaddress>\\\\d{1,3}\\\\.\\\\d{1,3}\\\\.\\\\d{1,3}\\\\.\\\\d{1,3})\"[$__interval])))"
    }
   ]
  },
  {
   "title": "Top Requested Pages",
   "type": "table",
   "gridPos": { "h": 6, "w": 15, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "topk(5,sum by (path) (count_over_time({filename=\"/var/log/nginx/access_loki.log\"} | regexp \"[GET|POST] (?P<path>.*?) HTTP\"[$__interval])))"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 19, "w": 9, "x": 15, "y": 32 },
   "targets": [
    {
     "expr": "{filename=\"/var/log/nginx/access_loki.log\"}"
    }
   ]
  },
  {
   "title": "Top User Agents",
   "type": "table",
   "gridPos": { "h": 6, "w": 15, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "topk(10, sum by (useragent) (count_over_time({filename=\"/var/log/nginx/access_loki.log\"} | regexp \"HTTP\\\\/1\\\\.1\\\" (?P<statuscode>\\\\d{3}) (?P<bytessent>\\\\d+) (?P<refferer>\\\".*?\\\") \\\"(?P<useragent>.*)\\\"\"[$__interval])))"
    }
   ]
  },
  {
   "title": "Referrer",
   "type": "table",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "topk(5, sum by (refferer) (count_over_time({filename=\"/var/log/nginx/access_loki.log\"} | regexp \"HTTP\\\\/1\\\\.1\\\" (?P<statuscode>\\\\d{3}) (?P<bytessent>\\\\d+) (?P<refferer>\\\".*?\\\") \\\"(?P<useragent>.*)\\\"\"[$__interval])))"
    }
   ]
  }
 ]
}